
[System.Serializable]
public class PythonSendInTask : PythonSendIn
{
    /// <summary>
    /// This task id, generated by python.
    /// </summary>
    public string taskId;
    
    /// <summary>
    /// If true, unity should respond to python even if task was successfully completed.
    /// </summary>
    public bool waitForResponse;
    
    /// <summary>
    /// Collection of commands to execute.
    /// Commands will be executed from first to last.
    /// </summary>
    public InDataCommand[] commands;
}
